---
title: "Capture-Mark-Resight non-spatial wirh RMark"
author: "Tati Micheletti"
date: "1 May 2018"
output: html_document
---

## Mabuyas

The present analysis focused on determining the density of mabuyas (*Trachylepis atlantica*) in different habitats on the island of Fernando de Noronha. The `R` package used for the present analysis is the `RMark` and the code is hosted in `github` (https://github.com/tati-micheletti/mabuyas). This `.rmd` file will guide you on how to reproduce the analysis. Make sure you also have program [Mark](http://www.phidot.org/software/mark/docs/book/) and [RStudio](www.rstudio.com) installed in your computer. Mark needs to be installed in the ProgramFiles folder (`C:\ProgramFiles\`).

### Getting your project
1. Go to [github website](https://github.com/tati-micheletti/mabuyas).
2. Click on the green button that says `clone or download`, and click on the `download ZIP` to download the folder.
3. Now you are set to start working on your project, so open the file `mabuyas.Rproj` in `RStudio`. 
4. Now, on the lower-right pannel, click on the file mabuyasAnalysis.Rmd and you will open this source file.
5. Run all code chuncks below by pressing `Ctrl + Alt + R` or clicking in `Run` and `Run All` in the tab above.

